# Generated by Django 3.0.1 on 2019-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
